plugins {
    id 'fabric-loom' version '1.14-SNAPSHOT'
    id 'java'
}

version = "${project.mod_version}+${project.minecraft_version}"
group   = project.maven_group

processResources {
    inputs.property "version", project.version
    filteringCharset = "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

base {
    archivesName = project.archives_base_name
}

repositories {
    maven { name = 'FabricMC'; url = 'https://maven.fabricmc.net/' }
    mavenCentral()
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

dependencies {
    minecraft    "com.mojang:minecraft:${project.minecraft_version}"
    mappings     loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
    modImplementation "maven.modrinth:Nv2fQJo5:lrnVIO9F"
}

loom {
    accessWidenerPath = file("src/main/resources/replay-to-world.accesswidener")
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
    options.release  = 21
}
